basic:
  url: http://localhost:8080

#bound of area where simulation is being processed
location:
  latitude:
    min: 50.063696
    max: 50.067456
  longitude:
    min: 19.916326
    max: 19.925553

simulation:
  unit:
    max: 2