osm.map.file.path: osm/map-kiev-pznk.osm

simulation:
  map.correction.reachable.max: 5.0
  cell.size: 2.0
  unit:
    max: 1000
    distance: 2

actuator:
  username: actuator
  password: f19f555c0d327ea86fef73c5efd09697

management.contextPath: /actuator
logging.file: log/artificial-city-simulator.log