osm.map.file.path: osm/map-czarn.osm

simulation:
  map.correction.reachable.max: 5.0
  cell.size: 2.0
  unit:
    distance: 2
    max: 3

basic.url: http://localhost:8080

actuator:
  username: actuator
  password: f19f555c0d327ea86fef73c5efd09697

management.contextPath: /actuator
