osm.map.file.path: osm/map-piastowska-debug.osm

simulation:
  map.correction.reachable.max: 5.0
  cell.size: 2.0
  unit:
    max: 10
    distance: 2
    import: true
    export: true

graph:
  import: true
  export: true

server:
  servlet.contextPath: /acs
  port: 8080

mongo:
  host: localhost
  port: 27017
  database.name: artificial-city-database

spring.profiles.active:

actuator:
  username: actuator
  password: f19f555c0d327ea86fef73c5efd09697

management.servlet.contextPath: /actuator
azure.basic.url: http://artificial-city-simulation.azurewebsites.net